language: node_js # 构建所需的语言环境
node_js:
  - "v12.13.1"  # 对应的版本
branches:
  only:
  - master    # 构建的分支
cache:
  directories:
  - node_modules # 依赖缓存的目录
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
# 安装环境
install:
  - npm i

# gitbook生成静态文件
script:
  - vite build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  local_dir: dist/
  target-branch: gh-pages
  verbose: true
  on:
    branch: master